name: audio_plugin_example
description: A sample to demonstrate the usage of import_js_library
version: 0.0.1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

  import_js_library:
    # When depending on this package from a real application you should use:
    #   injectjsplugin: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.github.florent37.pluginexample
        pluginClass: AudioPlugin
      ios:
        pluginClass: PluginexamplePlugin
      macos:
        pluginClass: PluginexamplePlugin
      web:
        pluginClass: AudioPlugin
        fileName: web/audio_plugin_web.dart

  assets:
    - assets/howler.js
